site_name: My Docs
theme:
  name: material
extra:
  version:
    provider: mike
plugins:
  - mike:
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js